### ISSUE TITLE
Reference allpairspy

### ISSUE THREAD

**Issue by fkromer** [bayandin/allpairs#2]
For users it is helpful to be guided to [thombashi/allpairspy](https://github.com/thombashi/allpairspy) ([allpairspy on pypi](https://pypi.python.org/pypi/allpairspy/2.4.0)). It is a fork of this repository ([AllPairs on pypi](https://pypi.python.org/pypi/AllPairs)) with more functionality and better documentation.

**Comment by bayandin** [comment]
Thanks @fkromer. I've updated repo description
